# Generated by Django 5.0.8 on 2024-08-12 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_stock_export_to_csv_stock_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
